name: Deploy acr infra

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call

permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 